#!/usr/bin/env bash
# SeederLinux Lite - Mirror worker
# The worker is intentionally not started during development. Run it from the
# installed server through api/index.php?action=mirror-sync-now.
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"
JOB_ID="${1:-}"

if [[ -z "${JOB_ID}" || ! "${JOB_ID}" =~ ^[0-9]+$ ]]; then
    printf 'Usage: %s JOB_ID\n' "$0" >&2
    exit 2
fi

if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # This file is generated by install/install.sh and is not user input.
    source "${ENV_FILE}"
    set +a
fi

DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-seederlinux}"
DB_USER="${DB_USER:-seeder}"
DB_PASS="${DB_PASS:-seeder123}"
PSQL=(psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -X -q -t -A -v ON_ERROR_STOP=1)
export PGPASSWORD="${DB_PASS}"

config_line="$(${PSQL[@]} -c "SELECT tool, mirror_base_path, enabled, path_locked, verify_gpg, sync_interval_hours, auto_cleanup_enabled, retention_snapshots, quarantine_days FROM mirror.config ORDER BY id LIMIT 1")"
if [[ -z "${config_line}" ]]; then
    echo "Mirror configuration not found" >&2
    exit 1
fi
IFS='|' read -r TOOL BASE_PATH ENABLED PATH_LOCKED VERIFY_GPG INTERVAL AUTO_CLEANUP RETENTION QUARANTINE_DAYS <<< "${config_line}"

BASE_PATH="${BASE_PATH:-/var/lib/seederlinux/mirror}"
LOG_DIR="${BASE_PATH}/log"
LOG_FILE="${LOG_DIR}/sync-${JOB_ID}.log"
mkdir -p "${BASE_PATH}/tmp" "${LOG_DIR}" "${BASE_PATH}/cache" "${BASE_PATH}/public" "${BASE_PATH}/quarantine"
touch "${LOG_FILE}"
exec >>"${LOG_FILE}" 2>&1

sql_value() {
    local value="$1"
    "${PSQL[@]}" -v value="${value}" -c "$2"
}

set_job() {
    local status="$1"
    local details="$2"
    "${PSQL[@]}" -v job_id="${JOB_ID}" -v job_status="${status}" -v job_details="${details}" \
        -c "UPDATE mirror.jobs SET status = :'job_status', details = :'job_details', finished_at = CASE WHEN :'job_status' IN ('success', 'error') THEN NOW() ELSE finished_at END WHERE id = :'job_id'"
}

mark_gpg_verified() {
    "${PSQL[@]}" -v job_id="${JOB_ID}" \
        -c "UPDATE mirror.jobs SET gpg_verified = TRUE WHERE id = :'job_id'"
}

verify_gpg_metadata() {
    [[ "${VERIFY_GPG,,}" == "t" || "${VERIFY_GPG,,}" == "true" || "${VERIFY_GPG}" == "1" ]] || return 0
    command -v gpg >/dev/null 2>&1 || { echo "GPG verification requested but gpg is not installed"; return 127; }

    case "${TOOL}" in
        aptly)
            # aptly validates signed repository metadata during mirror update.
            aptly mirror list >/dev/null
            ;;
        apt-mirror)
            find "${BASE_PATH}/public" -type f \( -name InRelease -o -name Release.gpg \) -print -quit | grep -q . || {
                echo "No signed APT metadata found under ${BASE_PATH}/public"
                return 1
            }
            ;;
    esac
    mark_gpg_verified
}

cleanup_quarantine() {
    local cleanup_job_id
    cleanup_job_id="$(${PSQL[@]} -c "INSERT INTO mirror.jobs (job_type, status, started_at) VALUES ('cleanup', 'running', NOW()) RETURNING id")"
    local cleanup_details=""
    local cleanup_status="success"
    local cutoff
    cutoff="$(date -d "-${QUARANTINE_DAYS:-7} days" '+%s')"

    while IFS= read -r item; do
        [[ -z "${item}" ]] && continue
        local item_name item_stamp
        item_name="$(basename "${item}")"
        item_stamp="$(stat -c %Y "${item}" 2>/dev/null || echo 0)"
        if (( item_stamp > 0 && item_stamp < cutoff )); then
            rm -rf -- "${item}"
            cleanup_details+="removed=${item_name};"
        fi
    done < <(find "${BASE_PATH}/quarantine" -mindepth 1 -maxdepth 1 -print 2>/dev/null)

    if [[ "${TOOL}" == "aptly" ]]; then
        local keep="${RETENTION:-2}"
        mapfile -t snapshots < <(aptly snapshot list -raw 2>/dev/null | grep '^seeder-' | sort -r || true)
        if (( ${#snapshots[@]} > keep )); then
            for snapshot in "${snapshots[@]:keep}"; do
                local quarantine_entry="${BASE_PATH}/quarantine/${snapshot}.snapshot"
                mkdir -p "${quarantine_entry}"
                printf 'snapshot=%s\nquarantined_at=%s\n' "${snapshot}" "$(date --iso-8601=seconds)" > "${quarantine_entry}/manifest"
                aptly snapshot drop -force "${snapshot}" || cleanup_status="error"
                cleanup_details+="snapshot=${snapshot};"
            done
        fi
    fi

    [[ -z "${cleanup_details}" ]] && cleanup_details="nothing_to_remove"
    "${PSQL[@]}" -v cleanup_id="${cleanup_job_id}" -v cleanup_status="${cleanup_status}" -v cleanup_details="${cleanup_details}" \
        -c "UPDATE mirror.jobs SET status = :'cleanup_status', details = :'cleanup_details', finished_at = NOW() WHERE id = :'cleanup_id'"
    [[ "${cleanup_status}" == "success" ]]
}

run_aptly() {
    command -v aptly >/dev/null 2>&1 || { echo "aptly is not installed; see docs/MIRROR.md"; return 127; }
    local distro_id distro_name distro_version distro_codename source_url mirror_name snapshot_name
    while IFS='|' read -r distro_id distro_name distro_version distro_codename source_url; do
        [[ -z "${distro_id}" || -z "${distro_version}" || -z "${source_url}" ]] && continue
        mirror_name="seeder-${distro_name}-${distro_version}"
        mirror_name="${mirror_name// /-}"
        snapshot_name="${mirror_name}-$(date +%Y%m%d%H%M%S)"
        if ! aptly mirror show "${mirror_name}" >/dev/null 2>&1; then
            aptly mirror create "${mirror_name}" "${source_url}" "${distro_version}" main
        fi
        aptly mirror update "${mirror_name}"
        aptly snapshot create "${snapshot_name}" from mirror "${mirror_name}"
        # Publishing is idempotent when the distribution already exists.
        aptly publish snapshot "${snapshot_name}" "${distro_version}" || \
            aptly publish snapshot -force-overwrite "${snapshot_name}" "${distro_version}"
    done < <("${PSQL[@]}" -c "SELECT d.id, d.name, v.version, d.codename, COALESCE(NULLIF(ov.value, ''), '') FROM mirror.distros d JOIN mirror.versions v ON v.distro_id = d.id LEFT JOIN mirror.organization_repository_settings ors ON ors.use_local_mirror = TRUE LEFT JOIN public.organization_variables ov ON ov.organization_id = ors.organization_id AND ov.variable_id = (SELECT id FROM public.variable_definitions WHERE name = CASE WHEN d.name = 'Debian' THEN 'REPOSITORY_DEBIAN_URL' WHEN d.name = 'Ubuntu' THEN 'REPOSITORY_UBUNTU_URL' WHEN d.name = 'Linux Mint' THEN 'REPOSITORY_MINT_URL' WHEN d.name = 'Zorin' THEN 'REPOSITORY_ZORIN_URL' END) WHERE d.active = TRUE AND v.active = TRUE GROUP BY d.id, d.name, v.version, d.codename, ov.value ORDER BY d.name, v.version")
}

run_apt_mirror() {
    command -v apt-mirror >/dev/null 2>&1 || { echo "apt-mirror is not installed; see docs/MIRROR.md"; return 127; }
    mkdir -p "${BASE_PATH}/public"
    local mirror_conf="${BASE_PATH}/tmp/apt-mirror.list"
    printf 'set base_path %s\n' "${BASE_PATH}" > "${mirror_conf}"
    while IFS='|' read -r distro_name distro_version source_url; do
        [[ -z "${source_url}" ]] && continue
        printf 'deb %s %s main contrib non-free\n' "${source_url}" "${distro_version}" >> "${mirror_conf}"
    done < <("${PSQL[@]}" -c "SELECT d.name, v.version, COALESCE(NULLIF(ov.value, ''), '') FROM mirror.distros d JOIN mirror.versions v ON v.distro_id = d.id LEFT JOIN mirror.organization_repository_settings ors ON ors.use_local_mirror = TRUE LEFT JOIN public.organization_variables ov ON ov.organization_id = ors.organization_id AND ov.variable_id = (SELECT id FROM public.variable_definitions WHERE name = CASE WHEN d.name = 'Debian' THEN 'REPOSITORY_DEBIAN_URL' WHEN d.name = 'Ubuntu' THEN 'REPOSITORY_UBUNTU_URL' WHEN d.name = 'Linux Mint' THEN 'REPOSITORY_MINT_URL' WHEN d.name = 'Zorin' THEN 'REPOSITORY_ZORIN_URL' END) WHERE d.active = TRUE AND v.active = TRUE GROUP BY d.name, v.version, ov.value")
    apt-mirror "${mirror_conf}"
    if [[ -x /var/spool/apt-mirror/var/clean.sh ]]; then
        /var/spool/apt-mirror/var/clean.sh
    fi
}

set_job running "worker_started tool=${TOOL}"
status=0
if [[ "${ENABLED,,}" != "t" && "${ENABLED,,}" != "true" && "${ENABLED}" != "1" ]]; then
    echo "Mirror is disabled"
    set_job error "mirror_disabled"
    exit 1
fi

case "${TOOL}" in
    aptly) run_aptly || status=$? ;;
    apt-mirror) run_apt_mirror || status=$? ;;
    *) echo "Unsupported mirror tool: ${TOOL}"; status=2 ;;
esac

if (( status == 0 )); then
    verify_gpg_metadata || status=$?
fi

if (( status == 0 )); then
    if [[ "${AUTO_CLEANUP,,}" == "t" || "${AUTO_CLEANUP,,}" == "true" || "${AUTO_CLEANUP}" == "1" ]]; then
        cleanup_quarantine || status=$?
    fi
fi

if (( status == 0 )); then
    set_job success "sync_completed log=${LOG_FILE}"
else
    set_job error "sync_failed exit=${status} log=${LOG_FILE}"
fi
exit "${status}"
